#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/laladesk/laladesk /usr/bin/laladesk
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/laladesk.service ]; then
			rm /etc/systemd/system/laladesk.service /usr/lib/systemd/system/laladesk.service /usr/lib/systemd/user/laladesk.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/laladesk/files/systemd/laladesk.service /usr/lib/systemd/system/laladesk.service
		# try fix error in Ubuntu 18.04
		# Failed to reload laladesk.service: Unit laladesk.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/laladesk.service:10: Executable path is not absolute: pkill -f "laladesk --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/laladesk.service
		fi
		systemctl daemon-reload
		systemctl enable laladesk
		systemctl start laladesk
	fi
fi
